name: Terraform Validation

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Run Terraform Validation
        run: |
          chmod +x validate_tf.sh
          ./validate_tf.sh
      
      - name: Commit Validation Results
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'Add validation results'
          add: 'validation_results.txt'
