name: Terraform Validation

on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run Terraform Validation
        run: |
          chmod +x validate_tf.sh
          ./validate_tf.sh

      - name: Configure Git
        run: |
          git config --global user.email "vamsi.sapireddy@outlook.com"
          git config --global user.name "vamsi560"
